# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(help_text='\n                                                                Format: yycc-iiii\n                                                                yy - year\n                                                                cc - class\n                                                                iiii - unique id', max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('task_class', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.Student'),
        ),
        migrations.AddField(
            model_name='result',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.Subject'),
        ),
    ]
