# Generated by Django 2.0.3 on 2018-03-26 17:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='result',
            name='student_reference',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='school_app.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='subject_reference',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='school_app.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
