# Generated by Django 2.0.3 on 2018-03-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_auto_20180326_2036'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student_reference', 'subject_reference')},
        ),
    ]
